import { Effect, Fiber, Layer } from "effect"
import { Docker, DockerError } from "@roci/core/services/Docker.js"
import { runPhases } from "@roci/core/core/phase-runner.js"
import { logToConsole, logBehavior } from "@roci/core/logging/log-writer.js"
import { ProjectRoot } from "@roci/core/services/ProjectRoot.js"
import { makeCharacterConfig } from "@roci/core/services/CharacterFs.js"
import { execSync } from "node:child_process"
import type { ResolvedDomain } from "./domains/registry.js"
import { OAuthToken } from "@roci/core/services/OAuthToken.js"
import type { ModelConfig } from "@roci/core/core/model-config.js"
import { provisionConsciousProvider } from "@roci/core/brain/cortex/conscious/opencode-config.js"
import { provisionMemoryCli } from "@roci/core/brain/limbic/hippocampus/memory/memory-cli.js"
import { provisionWmCli } from "@roci/core/brain/limbic/wm/wm-cli.js"
import { ensureWmFiles } from "@roci/core/brain/limbic/wm/wm-store.js"
import { DEFAULT_CORTEX_MODELS } from "@roci/core/model/handles.js"
import { launchEmbedServer, reapEmbedServers } from "./embed-server.js"
import { withSessionEnd } from "./session-end.js"

/**
 * Ensure a domain container exists and is running.
 * Container name: `roci-<domainName>`.
 * Returns the container ID.
 */
const ensureContainer = (containerName: string, rd: ResolvedDomain) =>
  Effect.gen(function* () {
    const docker = yield* Docker

    const existing = yield* docker.status(containerName)

    if (existing && existing.status === "running") {
      yield* logToConsole("orchestrator", "main", `Container ${containerName} already running`)
      return existing.id
    }

    if (existing && existing.status === "paused") {
      yield* docker.resume(containerName)
      yield* logToConsole("orchestrator", "main", `Container ${containerName} resumed`)
      return existing.id
    }

    // Remove old container if exists (exited/created)
    if (existing) {
      yield* docker.remove(containerName)
    }

    // Create the container with domain-specific mounts
    const containerId = yield* docker.create({
      name: containerName,
      image: rd.config.imageName,
      mounts: rd.config.containerMounts.map((m) => ({
        host: m.host,
        container: m.container,
        readonly: m.readonly,
      })),
      env: {
        ...(process.env.SKIP_FIREWALL ? { SKIP_FIREWALL: "1" } : {}),
      },
      cmd: ["bash", "-c", "if [ -z \"\$SKIP_FIREWALL\" ]; then sudo /usr/local/bin/init-firewall.sh; fi && sleep infinity"],
      capAdd: ["NET_ADMIN", "NET_RAW"],
    })

    // Start the container (containerId is generated by Docker, not user input)
    yield* Effect.try({
      try: () => {
        execSync(`docker start ${containerId}`, { stdio: "pipe" })
      },
      catch: (e) => new DockerError("Failed to start container", e),
    })

    // Run domain-specific container setup
    if (rd.config.containerSetup) {
      rd.config.containerSetup(containerId)
    }

    yield* logToConsole("orchestrator", "main", `Container ${containerName} created and started`)

    return containerId
  })

/**
 * Multi-domain orchestrator. Builds images, ensures per-domain containers,
 * spawns a Fiber per character, and waits for all to complete (or be interrupted).
 */
export const runOrchestrator = (resolvedDomains: ResolvedDomain[], tickIntervalSeconds: number, models: ModelConfig, manualApproval = false) =>
  Effect.gen(function* () {
    const projectRoot = yield* ProjectRoot
    const docker = yield* Docker

    const gitSha = yield* Effect.sync(() => {
      try {
        return execSync("git rev-parse --short HEAD", { stdio: "pipe" }).toString().trim()
      } catch {
        return "unknown"
      }
    })

    // Bring up the host long-term-memory embed server alongside the mlx tiers.
    // Placed HERE — the single chokepoint every start path funnels through
    // (`roci start` via startCommand AND bare `roci` via validateAndStart) — so
    // long-term memory comes up exactly once on every invocation, not only the
    // explicit `start` subcommand. Best-effort: a missing python env logs loud and
    // continues (error channel `never`); it must never block character startup.
    yield* launchEmbedServer(projectRoot)

    const totalChars = resolvedDomains.reduce((n, rd) => n + rd.characters.length, 0)
    yield* logToConsole(
      "orchestrator",
      "main",
      `Starting ${totalChars} character(s) across ${resolvedDomains.length} domain(s)...`,
    )

    // Token is managed by OAuthToken service — validated at layer startup
    const oauthService = yield* OAuthToken
    const { token: oauthToken } = yield* oauthService.getToken
    yield* logToConsole("orchestrator", "main", `OAuth token: ${oauthToken.slice(0, 12)}...`)

    // Build images — deduplicated by imageName
    const builtImages = new Set<string>()
    for (const rd of resolvedDomains) {
      if (builtImages.has(rd.config.imageName)) continue
      builtImages.add(rd.config.imageName)

      const dockerfilePath = rd.config.dockerfilePath
      const dockerContext = rd.config.dockerContext

      if (!dockerfilePath || !dockerContext) {
        yield* Effect.logError(`Domain ${rd.name} has no dockerfilePath/dockerContext configured`)
        continue
      }

      yield* logToConsole("orchestrator", "main", `Building Docker image ${rd.config.imageName}...`)
      yield* docker.build(
        rd.config.imageName,
        dockerfilePath,
        dockerContext,
      )
    }

    // Ensure per-domain containers
    const containerIds = new Map<string, string>()
    for (const rd of resolvedDomains) {
      const containerName = `roci-${rd.name}`
      const containerId = yield* ensureContainer(containerName, rd)
      containerIds.set(rd.name, containerId)

      yield* logBehavior("orchestrator", "main", "provision", { type: "provision", component: "container", status: "ready", detail: containerName })

      // Provision the local conscious-tier provider at startup so the `local`
      // opencode provider exists before any reflection (the `dreamCompression` role runs on it).
      // Idempotent; failure-tolerant — a provisioning failure only logs.
      yield* provisionConsciousProvider(containerId, DEFAULT_CORTEX_MODELS.conscious).pipe(
        Effect.tap(() => logBehavior("orchestrator", "main", "provision", { type: "provision", component: "conscious_provider", status: "ready" })),
        Effect.catchAll((e) =>
          logToConsole("orchestrator", "main", `conscious provider provisioning failed: ${e}`, "warn").pipe(
            Effect.zipRight(logBehavior("orchestrator", "main", "provision", { type: "provision", component: "conscious_provider", status: "failed", detail: String(e) })),
          ),
        ),
      )

      // Provision the in-container `memory` CLI EAGERLY at startup — core character
      // infrastructure must not be hot-loaded during the active loop. The
      // spacemolt startup-phase reflection runs a pre-cull promotion hook
      // (store.promote → `docker exec … memory promote`) BEFORE the cortex loop's
      // conscious-provision step, so a lazily-provisioned binary `exit 127`s there
      // and the subsequent dream cull overwrites diary.md, losing the raw entries.
      // Provisioning here (right after the container is up) closes that window.
      // Idempotent (overwrites the binary); needs only a running container + root
      // exec. Installs the built @roci/player-tools bundle verbatim — the per-run
      // embed endpoint is delivered as MEMORY_EMBED_URL at invocation time by
      // longterm-store (spec §3), not baked here. Failure-tolerant: a missing
      // bundle (misordered build) fails loud here — log loud and continue
      // (long-term memory degrades).
      yield* provisionMemoryCli(containerId).pipe(
        Effect.tap(() => logBehavior("orchestrator", "main", "provision", { type: "provision", component: "memory_cli", status: "ready" })),
        Effect.catchAll((e) =>
          logToConsole("orchestrator", "main", `memory CLI provisioning failed (long-term memory unavailable): ${e}`, "warn").pipe(
            Effect.zipRight(logBehavior("orchestrator", "main", "provision", { type: "provision", component: "memory_cli", status: "failed", detail: String(e) })),
          ),
        ),
      )

      // Provision the in-container `wm` CLI EAGERLY at startup, alongside
      // `memory` (spec §2: same no-lazy-provisioning rule — core character
      // infrastructure must exist before any phase runs). Idempotent
      // (overwrites the script); needs only a running container + root exec.
      // Failure-tolerant: log loud and continue (working memory degrades to
      // a read-only WM.md until the next start).
      yield* provisionWmCli(containerId).pipe(
        Effect.tap(() => logBehavior("orchestrator", "main", "provision", { type: "provision", component: "wm_cli", status: "ready" })),
        Effect.catchAll((e) =>
          logToConsole("orchestrator", "main", `wm CLI provisioning failed (working memory unavailable): ${e}`, "warn").pipe(
            Effect.zipRight(logBehavior("orchestrator", "main", "provision", { type: "provision", component: "wm_cli", status: "failed", detail: String(e) })),
          ),
        ),
      )

      // Seed each character's working-memory FILES (wm.json + WM.md) EAGERLY at
      // startup, alongside the `wm` CLI (same no-lazy-provisioning rule). Lifted
      // here from the conscious executor's first-turn provisioning so the cortex
      // layer holds no wm (limbic) host-code dependency. Idempotent — never
      // clobbers an existing wm.json/WM.md — and precedes the first tick on all
      // paths, so WM.md exists before any WM.md-dependent conscious request.
      // (Intentional micro-timing lift: seeding moves from first-conscious-turn to
      // container startup; behavior for the running loop is unchanged.)
      // Failure-tolerant: ensureWmFiles swallows its own errors; log ready per char.
      for (const charName of rd.characters) {
        const char = makeCharacterConfig(projectRoot, charName)
        yield* ensureWmFiles(char).pipe(
          Effect.tap(() => logBehavior(char.name, "main", "provision", { type: "provision", component: "wm_files", status: "ready" })),
          Effect.catchAll((e) =>
            logToConsole(char.name, "main", `wm files seeding failed (WM.md unavailable): ${e}`, "warn").pipe(
              Effect.zipRight(logBehavior(char.name, "main", "provision", { type: "provision", component: "wm_files", status: "failed", detail: String(e) })),
            ),
          ),
        )
      }
    }

    // Validate token inside first container — catches auth issues before any character starts.
    // Distinguish a genuine auth rejection from the container having died (e.g. the firewall
    // init script exited under `set -euo pipefail`), so the surfaced error is truthful.
    const firstContainerId = containerIds.values().next().value
    if (firstContainerId) {
      // Prefer the classified check; fall back to the boolean API for stubs.
      const outcome = oauthService.checkInContainer
        ? yield* oauthService.checkInContainer(firstContainerId)
        : ((yield* oauthService.validateInContainer(firstContainerId))
            ? ({ kind: "valid" } as const)
            : ({ kind: "auth-rejected", detail: "validateInContainer returned false" } as const))
      if (outcome.kind === "auth-rejected" || outcome.kind === "container-unavailable") {
        const message =
          outcome.kind === "auth-rejected"
            ? "OAuth token is not valid inside container. Run 'claude setup-token' and update .oauth-token"
            : `Container is not running, so the OAuth token could not be validated — the token may be fine. ` +
              `This usually means the container exited during startup (e.g. the firewall init script failed). ` +
              `Check 'docker logs roci-<domain>', or set SKIP_FIREWALL=1 to bypass the firewall. Detail: ${outcome.detail}`
        yield* logToConsole(
          "orchestrator",
          "main",
          `${message} — stopping containers and aborting`,
        )
        for (const [domainName] of containerIds) {
          yield* docker.stop(`roci-${domainName}`).pipe(Effect.catchAll(() => Effect.void))
        }
        return yield* Effect.fail(new DockerError(message))
      }
    }

    const containerEnv: Record<string, string> = {}

    // Fork character fibers
    const allFibers = []

    for (const rd of resolvedDomains) {
      const containerId = containerIds.get(rd.name)!

      for (const charName of rd.characters) {
        const char = makeCharacterConfig(projectRoot, charName)

        // Inline character loop: scoped phase runner
        const loopEffect = withSessionEnd(
          char.name,
          Effect.scoped(
            Effect.gen(function* () {
              yield* logToConsole(char.name, "orchestrator", "Starting character loop...")
              yield* logBehavior(char.name, "orchestrator", "main", {
                type: "session_start",
                domain: rd.name,
                character: char.name,
                gitSha,
                tickIntervalMs: tickIntervalSeconds * 1000,
              })

              yield* runPhases(
                {
                  char,
                  containerId,
                  containerEnv,
                  containerAddDirs: rd.config.containerAddDirs,
                  domainBundle: rd.config.bundle,
                  phaseData: {
                    ...(manualApproval ? { manualApproval: true } : {}),
                    models,
                  },
                },
                rd.config.phaseRegistry,
              )
            }),
          ),
        ).pipe(
          Effect.catchAll((e) =>
            logToConsole(charName, "orchestrator", `Fatal error: ${e}`),
          ),
        )

        // Each character gets a fresh (non-memoized) copy of the domain service
        // layer. Without Layer.fresh, Effect memoizes layers by reference, so all
        // characters in a domain share one allocation. For stateful services like
        // GameSocket (which hold a mutable WebSocket ref per connect() call), a
        // shared layer can cause one character's connect() to race with another's,
        // leading to stolen connections or lost login acks.
        const domainServiceLayer = rd.config.serviceLayer
          ? Layer.fresh(rd.config.serviceLayer)
          : undefined

        // Phase types erase R to `never` via cast, so loopEffect's R is already
        // satisfied. The layer is only needed at runtime for service resolution.
        const runnableLoop = domainServiceLayer
          ? (loopEffect.pipe(Effect.provide(domainServiceLayer)) as typeof loopEffect)
          : loopEffect

        const fiber = yield* Effect.fork(runnableLoop)
        allFibers.push(fiber)
      }
    }

    yield* logToConsole(
      "orchestrator",
      "main",
      `All ${allFibers.length} character(s) running. Press Ctrl-C to stop.`,
    )

    // Wait for all fibers (they run indefinitely until interrupted)
    // On exit (normal, error, or interrupt), stop all containers we created.
    yield* Fiber.joinAll(allFibers).pipe(
      Effect.ensuring(
        Effect.gen(function* () {
          yield* logToConsole("orchestrator", "main", "Shutting down — stopping containers...").pipe(
            Effect.catchAll(() => Effect.void),
          )
          // Reap the host embed server on the Effect shutdown path (graceful
          // SIGTERM; the synchronous reaper in main.ts is the SIGKILL backstop).
          // This is what tears the child down on a FATAL teardown where no OS
          // signal fires — mirroring the container stop just below, same path,
          // runs on normal exit, error, or interrupt.
          yield* Effect.sync(() => reapEmbedServers(undefined, "SIGTERM"))
          for (const [domainName] of containerIds) {
            const containerName = `roci-${domainName}`
            yield* docker.stop(containerName).pipe(
              Effect.tap(() => logToConsole("orchestrator", "main", `Container ${containerName} stopped`)),
              Effect.catchAll(() => Effect.void),
            )
          }
        }),
      ),
    )
  })
