import { Effect, Fiber, Layer } from "effect"
import { Docker, DockerError } from "@roci/core/services/Docker.js"
import { runPhases } from "@roci/core/core/phase-runner.js"
import { logToConsole } from "@roci/core/logging/log-writer.js"
import { ProjectRoot } from "@roci/core/services/ProjectRoot.js"
import { makeCharacterConfig } from "@roci/core/services/CharacterFs.js"
import { execSync } from "node:child_process"
import type { ResolvedDomain } from "./domains/registry.js"
import { OAuthToken } from "@roci/core/services/OAuthToken.js"
import type { ModelConfig } from "@roci/core/core/model-config.js"

/**
 * Ensure a domain container exists and is running.
 * Container name: `roci-<domainName>`.
 * Returns the container ID.
 */
const ensureContainer = (containerName: string, rd: ResolvedDomain) =>
  Effect.gen(function* () {
    const docker = yield* Docker

    const existing = yield* docker.status(containerName)

    if (existing && existing.status === "running") {
      yield* logToConsole("orchestrator", "main", `Container ${containerName} already running`)
      return existing.id
    }

    if (existing && existing.status === "paused") {
      yield* docker.resume(containerName)
      yield* logToConsole("orchestrator", "main", `Container ${containerName} resumed`)
      return existing.id
    }

    // Remove old container if exists (exited/created)
    if (existing) {
      yield* docker.remove(containerName)
    }

    // Create the container with domain-specific mounts
    const containerId = yield* docker.create({
      name: containerName,
      image: rd.config.imageName,
      mounts: rd.config.containerMounts.map((m) => ({
        host: m.host,
        container: m.container,
        readonly: m.readonly,
      })),
      env: {
        ...(process.env.SKIP_FIREWALL ? { SKIP_FIREWALL: "1" } : {}),
      },
      cmd: ["bash", "-c", "if [ -z \"\$SKIP_FIREWALL\" ]; then sudo /usr/local/bin/init-firewall.sh; fi && sleep infinity"],
      capAdd: ["NET_ADMIN", "NET_RAW"],
    })

    // Start the container (containerId is generated by Docker, not user input)
    yield* Effect.try({
      try: () => {
        execSync(`docker start ${containerId}`, { stdio: "pipe" })
      },
      catch: (e) => new DockerError("Failed to start container", e),
    })

    // Run domain-specific container setup
    if (rd.config.containerSetup) {
      rd.config.containerSetup(containerId)
    }

    yield* logToConsole("orchestrator", "main", `Container ${containerName} created and started`)

    return containerId
  })

/**
 * Multi-domain orchestrator. Builds images, ensures per-domain containers,
 * spawns a Fiber per character, and waits for all to complete (or be interrupted).
 */
export const runOrchestrator = (resolvedDomains: ResolvedDomain[], tickIntervalSeconds: number, models: ModelConfig, manualApproval = false) =>
  Effect.gen(function* () {
    const projectRoot = yield* ProjectRoot
    const docker = yield* Docker

    const totalChars = resolvedDomains.reduce((n, rd) => n + rd.characters.length, 0)
    yield* logToConsole(
      "orchestrator",
      "main",
      `Starting ${totalChars} character(s) across ${resolvedDomains.length} domain(s)...`,
    )

    // Token is managed by OAuthToken service — validated at layer startup
    const oauthService = yield* OAuthToken
    const { token: oauthToken } = yield* oauthService.getToken
    yield* logToConsole("orchestrator", "main", `OAuth token: ${oauthToken.slice(0, 12)}...`)

    // Build images — deduplicated by imageName
    const builtImages = new Set<string>()
    for (const rd of resolvedDomains) {
      if (builtImages.has(rd.config.imageName)) continue
      builtImages.add(rd.config.imageName)

      const dockerfilePath = rd.config.dockerfilePath
      const dockerContext = rd.config.dockerContext

      if (!dockerfilePath || !dockerContext) {
        yield* Effect.logError(`Domain ${rd.name} has no dockerfilePath/dockerContext configured`)
        continue
      }

      yield* logToConsole("orchestrator", "main", `Building Docker image ${rd.config.imageName}...`)
      yield* docker.build(
        rd.config.imageName,
        dockerfilePath,
        dockerContext,
      )
    }

    // Ensure per-domain containers
    const containerIds = new Map<string, string>()
    for (const rd of resolvedDomains) {
      const containerName = `roci-${rd.name}`
      const containerId = yield* ensureContainer(containerName, rd)
      containerIds.set(rd.name, containerId)
    }

    // Validate token inside first container — catches auth issues before any character starts
    const firstContainerId = containerIds.values().next().value
    if (firstContainerId) {
      const valid = yield* oauthService.validateInContainer(firstContainerId)
      if (!valid) {
        yield* logToConsole("orchestrator", "main", "OAuth token is not valid inside container — stopping containers and aborting")
        for (const [domainName] of containerIds) {
          yield* docker.stop(`roci-${domainName}`).pipe(Effect.catchAll(() => Effect.void))
        }
        return yield* Effect.fail(new DockerError("OAuth token is not valid inside container. Run 'claude setup-token' and update .oauth-token"))
      }
    }

    const containerEnv: Record<string, string> = {}

    // Fork character fibers
    const allFibers = []

    for (const rd of resolvedDomains) {
      const containerId = containerIds.get(rd.name)!

      for (const charName of rd.characters) {
        const char = makeCharacterConfig(projectRoot, charName)

        // Inline character loop: scoped phase runner
        const loopEffect = Effect.scoped(
          Effect.gen(function* () {
            yield* logToConsole(char.name, "orchestrator", "Starting character loop...")

            yield* runPhases(
              {
                char,
                containerId,
                containerEnv,
                containerAddDirs: rd.config.containerAddDirs,
                domainBundle: rd.config.bundle,
                phaseData: {
                  ...(manualApproval ? { manualApproval: true } : {}),
                  models,
                },
              },
              rd.config.phaseRegistry,
            )
          }),
        ).pipe(
          Effect.catchAll((e) =>
            logToConsole(charName, "orchestrator", `Fatal error: ${e}`),
          ),
        )

        // Each character gets a fresh (non-memoized) copy of the domain service
        // layer. Without Layer.fresh, Effect memoizes layers by reference, so all
        // characters in a domain share one allocation. For stateful services like
        // GameSocket (which hold a mutable WebSocket ref per connect() call), a
        // shared layer can cause one character's connect() to race with another's,
        // leading to stolen connections or lost login acks.
        const domainServiceLayer = rd.config.serviceLayer
          ? Layer.fresh(rd.config.serviceLayer)
          : undefined

        // Phase types erase R to `never` via cast, so loopEffect's R is already
        // satisfied. The layer is only needed at runtime for service resolution.
        const runnableLoop = domainServiceLayer
          ? (loopEffect.pipe(Effect.provide(domainServiceLayer)) as typeof loopEffect)
          : loopEffect

        const fiber = yield* Effect.fork(runnableLoop)
        allFibers.push(fiber)
      }
    }

    yield* logToConsole(
      "orchestrator",
      "main",
      `All ${allFibers.length} character(s) running. Press Ctrl-C to stop.`,
    )

    // Wait for all fibers (they run indefinitely until interrupted)
    // On exit (normal, error, or interrupt), stop all containers we created.
    yield* Fiber.joinAll(allFibers).pipe(
      Effect.ensuring(
        Effect.gen(function* () {
          yield* logToConsole("orchestrator", "main", "Shutting down — stopping containers...").pipe(
            Effect.catchAll(() => Effect.void),
          )
          for (const [domainName] of containerIds) {
            const containerName = `roci-${domainName}`
            yield* docker.stop(containerName).pipe(
              Effect.tap(() => logToConsole("orchestrator", "main", `Container ${containerName} stopped`)),
              Effect.catchAll(() => Effect.void),
            )
          }
        }),
      ),
    )
  })
