import { Effect, Fiber } from "effect"
import { Docker, DockerError } from "./services/Docker.js"
import { runPhases } from "./core/phase-runner.js"
import { logToConsole } from "./logging/console-renderer.js"
import { ProjectRoot } from "./services/ProjectRoot.js"
import { makeCharacterConfig } from "./services/CharacterFs.js"
import { readFileSync } from "node:fs"
import { execSync } from "node:child_process"
import * as path from "node:path"
import type { ResolvedDomain } from "./domains/registry.js"

/** Read a key=value .env file, returning a Record. */
function loadDotenv(projectRoot: string): Record<string, string> {
  try {
    const content = readFileSync(path.resolve(projectRoot, ".env"), "utf-8")
    const env: Record<string, string> = {}
    for (const line of content.split("\n")) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith("#")) continue
      const eq = trimmed.indexOf("=")
      if (eq === -1) continue
      const key = trimmed.slice(0, eq).trim()
      let val = trimmed.slice(eq + 1).trim()
      // Strip surrounding quotes
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1)
      }
      env[key] = val
    }
    return env
  } catch {
    return {}
  }
}

/**
 * Ensure a domain container exists and is running.
 * Container name: `roci-<domainName>`.
 * Returns the container ID.
 */
const ensureContainer = (containerName: string, rd: ResolvedDomain) =>
  Effect.gen(function* () {
    const docker = yield* Docker

    const existing = yield* docker.status(containerName)

    if (existing && existing.status === "running") {
      yield* logToConsole("orchestrator", "main", `Container ${containerName} already running`)
      return existing.id
    }

    if (existing && existing.status === "paused") {
      yield* docker.resume(containerName)
      yield* logToConsole("orchestrator", "main", `Container ${containerName} resumed`)
      return existing.id
    }

    // Remove old container if exists (exited/created)
    if (existing) {
      yield* docker.remove(containerName)
    }

    // Build env for container — include ROCI_ADD_DIRS if configured
    const containerCreateEnv: Record<string, string> = {}
    const addDirs = rd.config.containerAddDirs
    if (addDirs && addDirs.length > 0) {
      containerCreateEnv.ROCI_ADD_DIRS = addDirs.join(":")
    }

    // Create the container with domain-specific mounts
    const containerId = yield* docker.create({
      name: containerName,
      image: rd.config.imageName,
      mounts: rd.config.containerMounts.map((m) => ({
        host: m.host,
        container: m.container,
        readonly: m.readonly,
      })),
      env: containerCreateEnv,
      cmd: ["bash", "-c", "sudo /usr/local/bin/init-firewall.sh && sleep infinity"],
      capAdd: ["NET_ADMIN", "NET_RAW"],
    })

    // Start the container (containerId is generated by Docker, not user input)
    yield* Effect.try({
      try: () => {
        execSync(`docker start ${containerId}`, { stdio: "pipe" })
      },
      catch: (e) => new DockerError("Failed to start container", e),
    })

    // Run domain-specific container setup
    if (rd.config.containerSetup) {
      rd.config.containerSetup(containerId)
    }

    yield* logToConsole("orchestrator", "main", `Container ${containerName} created and started`)

    return containerId
  })

/**
 * Multi-domain orchestrator. Builds images, ensures per-domain containers,
 * spawns a Fiber per character, and waits for all to complete (or be interrupted).
 */
export const runOrchestrator = (resolvedDomains: ResolvedDomain[], tickIntervalSeconds: number, manualApproval = false) =>
  Effect.gen(function* () {
    const projectRoot = yield* ProjectRoot
    const docker = yield* Docker

    const totalChars = resolvedDomains.reduce((n, rd) => n + rd.characters.length, 0)
    yield* logToConsole(
      "orchestrator",
      "main",
      `Starting ${totalChars} character(s) across ${resolvedDomains.length} domain(s)...`,
    )

    // Load CLAUDE_CODE_OAUTH_TOKEN from .env
    const dotenv = loadDotenv(projectRoot)
    const oauthToken = dotenv.CLAUDE_CODE_OAUTH_TOKEN ?? process.env.CLAUDE_CODE_OAUTH_TOKEN
    if (!oauthToken) {
      yield* logToConsole("orchestrator", "main", "ERROR: CLAUDE_CODE_OAUTH_TOKEN not found in .env or environment")
      return yield* Effect.fail(
        new DockerError("CLAUDE_CODE_OAUTH_TOKEN not found in .env or environment"),
      )
    }
    const containerEnv = { CLAUDE_CODE_OAUTH_TOKEN: oauthToken }

    // Build images — deduplicated by imageName
    const builtImages = new Set<string>()
    for (const rd of resolvedDomains) {
      if (builtImages.has(rd.config.imageName)) continue
      builtImages.add(rd.config.imageName)

      const dockerfilePath = rd.config.dockerfilePath
      const dockerContext = rd.config.dockerContext

      if (!dockerfilePath || !dockerContext) {
        yield* Effect.logError(`Domain ${rd.name} has no dockerfilePath/dockerContext configured`)
        continue
      }

      yield* logToConsole("orchestrator", "main", `Building Docker image ${rd.config.imageName}...`)
      yield* docker.build(
        rd.config.imageName,
        dockerfilePath,
        dockerContext,
      )
    }

    // Ensure per-domain containers and fork character fibers
    const allFibers = []

    for (const rd of resolvedDomains) {
      const containerName = `roci-${rd.name}`
      const containerId = yield* ensureContainer(containerName, rd)

      // Build the per-character service layer with domain-specific services
      const domainServiceLayer = rd.config.serviceLayer

      for (const charName of rd.characters) {
        const char = makeCharacterConfig(projectRoot, charName)

        // Inline character loop: scoped phase runner
        const loopEffect = Effect.scoped(
          Effect.gen(function* () {
            yield* logToConsole(char.name, "orchestrator", "Starting character loop...")

            yield* runPhases(
              {
                char,
                containerId,
                containerEnv,
                domainBundle: rd.config.bundle,
                phaseData: manualApproval ? { manualApproval: true } : undefined,
              },
              rd.config.phaseRegistry,
            )
          }),
        ).pipe(
          Effect.catchAll((e) =>
            logToConsole(charName, "orchestrator", `Fatal error: ${e}`),
          ),
        )

        // Phase types erase R to `never` via cast, so loopEffect's R is already
        // satisfied. The layer is only needed at runtime for service resolution.
        const runnableLoop = domainServiceLayer
          ? (loopEffect.pipe(Effect.provide(domainServiceLayer)) as typeof loopEffect)
          : loopEffect

        const fiber = yield* Effect.fork(runnableLoop)
        allFibers.push(fiber)
      }
    }

    yield* logToConsole(
      "orchestrator",
      "main",
      `All ${allFibers.length} character(s) running. Press Ctrl-C to stop.`,
    )

    // Wait for all fibers (they run indefinitely until interrupted)
    yield* Fiber.joinAll(allFibers)
  })
